project:
  type: website
  output-dir: docs

website:
  title: "Data Science & Bioinformatics Portfolio"
  favicon: ./img/favicon-32x32.png
  repo-url: https://github.com/corvidfox/corvidfox.github.io/
  repo-actions: [source, issue]
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - text: About
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - icon: github
        text: GitHub
        href: https://github.com/corvidfox
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/morrigan-mahady-6b640712b
      - icon: envelope-at-fill
        text: Email
        href: mailto:anmorrigan@proton.me

format:
  html:
    theme:
      light: [cosmo, styles/light-mode.scss]
      dark: [cosmo, styles/dark-mode.scss]
    respect-user-color-scheme: true
    theme-toggle: true
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    code-fold: true
    code-summary: "Show Code"

execute:
  python: qmd_profile_py_env