project:
  type: website
  output-dir: _pages

website:
  title: "Test Homepage - Quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sections/about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



