project:
  type: website
  output-dir: docs

website:
  title: "Data Science & Bioinformatics Portfolio"
  favicon: https://github.com/corvidfox/corvidfox.github.io/blob/main/img/favicon-32x32.png
  repo-url: https://github.com/corvidfox/corvidfox.github.io/
  repo-actions: [source, issue]
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
#      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true