---
title: "About Morri"
# Placeholder until I might get an actual headshot
description: "This is Lucy, head of morale. She handles public relations. Morri handles the code."
#description: "Cross-disciplinaray insights driven by curiosity. Grounded in code, focused on results."
image: https://avatars.githubusercontent.com/u/107103167
image-alt: "A photograph of a black shiba inu wearing a flowered collar."
about:
    template: trestles
    image-shape: round
    links:
        - icon: github
          text: GitHub
          href: https://github.com/corvidfox
        - icon: linkedin
          text: LinkedIn
          href: https://www.linkedin.com/in/morrigan-mahady-6b640712b
        - icon: envelope-at
          text: Email
          href: mailto:anmorrigan@proton.me

---

:::{#hero-heading}

## Bio

Hi — I’m Morri, a data scientist with a clinical background, an MPH in progress, and a serious love of health data. I work at the intersection of epidemiology, bioinformatics, and analytics, building tools that make large, messy datasets more useful for research and public health. I’m mainly excited by omics, reproducibility, and clever ways to reduce human effort without sacrificing rigor.

Before pivoting to data science, I was as a critical care nurse and educator — so I know my way around both a CRRT machine and a good data pipeline. My projects range from fuzzy-matching patient records across data sets, to meta-analyzing EWAS studies, to modeling viral phylogenies for vaccine strain selection.

I care deeply about clarity, collaboration, and doing science that’s useful. I’d love to work on research teams, data-heavy health projects, or anything that needs solid analysis and a thoughtful partner.

## Education

- **_MPH_ in Epidemiology**, In Progress (Est. December 2025)  
  *[University of Texas Health Sciences Center, School of Public Health](https://sph.uth.edu/campuses/houston)* (*Houston, TX, USA*)\
  **Certificate:** [Genomics & Bioinformatics](https://catalog.uth.edu/public-health/programs/graduate-certificates/genomics-bioinformatics/)\
  **Certificate:** [Data Science](https://catalog.uth.edu/public-health/programs/graduate-certificates/data-science/)\
  **Thesis:** Epigenome-Wide Associations of Factor VIII and Von Willebrand Factor Levels (In Progress, Meta-Analysis, [de Vries Lab](https://sph.uth.edu/research/research-labs/?lab=DBYQRrcen7C%2B0xL/F4sxVD2//fX56uR77SeG7E1SnlQ=))

- **_BSc_ in Nursing**, 2019  
  *[University of Texas at Arlington](https://www.uta.edu/academics/schools-colleges/conhi)* (*Arlington, TX, USA*)

- **_BSc_ in Biology**, 2013  
  *[University of Texas at Dallas](https://www.utdallas.edu/)* (*Richardson, TX, USA*)\  
  **Minor:** Sociology

## Work Experience

- **Graduate Research Assistant**, February 2023 - Present  
  *[UTHealth Sciences Center, School of Public Health](https://sph.uth.edu/campuses/houston)* (*Houston, TX, USA*) \
  - **PI:** [Dr. M. Brad Cannell](
https://www.bradcannell.com/)
  - Contributed to public health research projects ([DETECT](https://github.com/brad-cannell/detect_fu_interviews_public), [DETECT-RPC](https://clinicaltrials.gov/study/NCT05958654), [Link2Care](https://github.com/corvidfox/link2care_public)), supporting the full data lifecycle — from collection and cleaning to analysis and reporting.
  - Developed and implemented probabilistic fuzzy-matching techniques using the fastLink R package to link subject data across datasets lacking common identifiers.
  - Drafted statistical analysis plans, IRB protocols, informed consent forms, and conducted statistical analyses in R. 

- **Critical Care Travel Nurse**, March 2021 - December 2022  
  *[Travel Nurse Across America](https://tnaa.com/)*, *USA* \
  - Rapidly deployed to hospitals nationwide, delivering expert-level critical care in ICU and ED settings, managing complex cases across multiple specialties. 
  - Led interdisciplinary teams, acted as Charge Nurse and educator, and routinely utilized advanced technologies (e.g. ECMO, IABP, CRRT, Impella, and Blakemore/Compass, etc.)   

- **Registered Nurse (Residency)**, March 2020 - March 2021  
  *[Rochester General Hospital](https://www.plano.gov/168/9-1-1-Public-Safety-Communications)*, *Rochester, NY, USA*
 
- **Public Safety Communications Specialist**, February 2018 - February 2020  
  *[City of Plano](https://www.plano.gov/168/9-1-1-Public-Safety-Communications)*, *Plano, TX, USA*

:::